### ISSUE TITLE
mkdir: cannot create directory Error is Visible 

### ISSUE THREAD

**Issue by Mitesh411** [foo-software/lighthouse-check-action#104]
**Describe the bug**
Implemented below  .yml File but Failed in Pipeline 

`name: Lighthouse
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir ${{ github.workspace }}/tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://www.foo.software,https://www.google.com'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts`

**To Reproduce**
Please Do Navigate the Link:- https://github.com/Mitesh411/Lighthouse-Demo/blob/main/.github/workflows/blank.yml

**Expected behavior**
The folder should be created in /tmp/artifacts

**Additional context**
Screen short are attached 
![screenshot-github com-2022 08 11-09_40_04](https://user-images.githubusercontent.com/6998472/184063531-0b3c91f2-e1ac-4b07-94f4-1ce4e7ee94ef.png)
![screenshot-github com-2022 08 11-09_39_38](https://user-images.githubusercontent.com/6998472/184063538-6f1c800b-29b6-4922-8065-f4771253a3cf.png)

**Comment by adamhenson** [comment]
Hi @Mitesh411 - this isn't related to Lighthouse Check GitHub action as I can see the failure occurs before the Lighthouse Check. Although we are using it in our documentation, so I'm hoping the below will help.

The error is occurring in the `mkdir` command within the `ubuntu-latest` container. Though it's not related to Lighthouse Check - I am curious why this issue is happening as it didn't happen in the past. Perhaps the `tmp` directory existed in older GitHub Runners and does not in more current versions.

Please try the below command instead (to use `-p` which will create any subdirectories):

```
mkdir -p ${{ github.workspace }}/tmp/artifacts
```

I think the above will work and since this issue isn't directly related to Lighthouse Check - I'm closing this issue. But please do confirm here that the above works (or doesn't). I'll also update our documentation to reflect the above.

**Comment by adamhenson** [comment]
Updated the [documentation](https://www.foo.software/docs/lighthouse-check-github-action/examples).

**Comment by Mitesh411** [comment]
It is now Working @adamhenson  **Thank you** for helping me out 


![mkdir -p is working](https://user-images.githubusercontent.com/6998472/184270975-0f6703ac-4b06-4ce0-9a84-2f1d23370920.png)

**Comment by adamhenson** [comment]
Glad it worked and thanks for opening the issue. Our docs should have good examples, so sooty for the confusion and glad we got to the bottom of it.
