### ISSUE TITLE
Result of 0 won't fail lighthouse-check-status-action

### ISSUE THREAD

**Issue by schoenwaldnils** [foo-software/lighthouse-check-action#16]
Like title says, when the page returns 404 or 502 or similar the test result is 0 on every audit part.
I currently have some problems with my on AWS deployed PRs. That's why I got the 0 result.

Nonetheless the lighthouse check action completed positive.

See: https://github.com/schoenwaldnils/timeline/pull/18/checks?check_run_id=550636083

**Comment by adamhenson** [comment]
Thanks for reporting @schoenwaldnils - looking into.

**Comment by adamhenson** [comment]
Thanks again @schoenwaldnils. This is now fixed with a PR in [foo-software/lighthouse-check](https://github.com/foo-software/lighthouse-check/pull/22). The `0` value was mistakenly passing in a condition as falsey... so, we needed to add more strict type detection. I previously reproduced [here](https://github.com/foo-software/lighthouse-check-action/runs/552976869?check_suite_focus=true) and confirmed the fix [here](https://github.com/foo-software/lighthouse-check-action/runs/553080575?check_suite_focus=true).
