### ISSUE TITLE
Specify which permissions need to be set for the access token (repo > public_repo) in docs

### ISSUE THREAD

**Issue by lukasoppermann** [foo-software/lighthouse-check-action#36]
If you can let me know what is needed, I can send a PR to the docs.

**Comment by lukasoppermann** [comment]
As far as I have figured out you only need the "repo > public_repo" scope in the personal access token

**Comment by adamhenson** [comment]
Hey @lukasoppermann - thanks for opening this. The token permission isn’t specific to this GitHub action. These permissions are whatever GitHub API requires to post comments. Since it’s not specific to this project I’d hesitate to add these details since they could change in the future. I think it might be nice to provide a link to where this is documented in the API, but to be honest I’m not even sure myself. If you can find this documentation and open a PR to link to it, I’d be grateful. I do remember having a hard time finding it and maybe just ended up guessing. I’ll try again and will post here if I find it.

**Comment by adamhenson** [comment]
This is the [documentation for the GitHub API endpoint](https://docs.github.com/en/rest/reference/repos#create-a-commit-comment) we use. I'm using `repo` and `write:discussion` scopes, however I might only need `repo`. Additional scopes might be relevant depending on circumstances. We might just want to link to the [OAuth scope documentation](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes) and hint that they will **most likely** need `repo` scope set on the token at minimum.

**Comment by adamhenson** [comment]
Important to note - not everyone will want or need `public_repo` scope.
